import { join, posix, sep } from 'node:path';
import type { ArtifactType } from './schema.js';
import type { ImportedSource } from './upstream.js';
import type { ResolvedStack } from './resolver.js';
import type { Selection, SelectedArtifact } from './selector.js';

export const MANIFEST_PATH = posix.join('.claude', 'agent-stack-manifest.json');
/** The markers an earlier version wrote around its block in CLAUDE.md. */
export const BEGIN_MARKER = '<!-- agent-stack:begin - generated by agent-stack, do not edit by hand -->';
export const END_MARKER = '<!-- agent-stack:end -->';
export const AGENTS_MD_PATH = 'AGENTS.md';

export interface PlannedFile {
  path: string;
  /** A knowledge file, copied byte for byte. Every artifact takes this path. */
  copyFrom: string;
}

export interface Manifest {
  generator: string;
  generatedAt: string;
  stack: { id: string; origin: string }[];
  rules: { id: string; path: string }[];
  skills: { id: string; path: string }[];
  commands: { id: string; path: string }[];
  /** Other generated paths this run owns, e.g. third-party licence notices. */
  extras: string[];
  /**
   * Content this project carries from other repositories, with the copyright and
   * licence it is redistributed under. This is where the upstream notices live.
   */
  imported: {
    source: string;
    repo: string;
    ref: string;
    license: string;
    licenseUrl: string;
    copyright: string;
  }[];
  /**
   * sha256 of every copied file, by its path in the project. It is how the next
   * run tells its own output from a file the project has edited since. Absent
   * from a manifest written before it existed, and added by `emit`, which is
   * the module that reads the bytes.
   */
  checksums?: Record<string, string>;
}

export interface ComposedOutput {
  /** The copied files. The manifest is written by `emit`. */
  files: PlannedFile[];
  manifest: Manifest;
  /**
   * The template that seeds AGENTS.md, copied byte for byte — but only when the
   * project has no AGENTS.md. It is kept out of `files` on purpose: those are
   * owned, checksummed and replaced, and this file stops being agent-stack's
   * the moment it is written.
   */
  agentsMd?: PlannedFile;
}

/** The file's own name under `knowledge/` is the name emitted under `.claude/`. */
/**
 * Where an artifact lands. The path under `knowledge/` decided the id, and the
 * id is the filename here — nothing about the file itself is inspected.
 */
function rulePath(entry: SelectedArtifact): string {
  return posix.join('.claude', 'rules', `${entry.artifact.meta.id}.md`);
}

function skillDir(entry: SelectedArtifact): string {
  return posix.join('.claude', 'skills', entry.artifact.meta.id);
}

function commandPath(entry: SelectedArtifact): string {
  return posix.join('.claude', 'commands', `${entry.artifact.meta.id}.md`);
}

/**
 * A CLAUDE.md with agent-stack's block taken out, or undefined when there is no
 * block to take out.
 *
 * agent-stack no longer writes CLAUDE.md — Claude Code reads AGENTS.md, but only
 * while no CLAUDE.md exists — so the block an earlier version wrote is the one
 * thing left to clean up. Only the text between the markers goes: everything
 * around it is the project's.
 */
export function withoutManagedBlock(existing: string): string | undefined {
  const begin = existing.indexOf(BEGIN_MARKER);
  const end = existing.indexOf(END_MARKER);
  if (begin < 0 || end < begin) return undefined;

  const before = existing.slice(0, begin).replace(/\s+$/, '');
  const after = existing.slice(end + END_MARKER.length).replace(/^\s+/, '');
  const rest = [before, after].filter((part) => part !== '').join('\n\n').replace(/\s+$/, '');
  return rest === '' ? '' : `${rest}\n`;
}

export function compose(
  stack: ResolvedStack,
  selection: Selection,
  generatorVersion: string,
  imported: ImportedSource[] = [],
): ComposedOutput {
  const files: PlannedFile[] = [];

  // Claude Code loads `.claude/rules/` on its own, honouring each rule's
  // `paths:` scope, so a rule needs no import from anywhere.
  const ruleEntries: { id: string; path: string }[] = [];
  for (const entry of selection.rules) {
    files.push({ path: rulePath(entry), copyFrom: entry.artifact.path });
    ruleEntries.push({ id: entry.artifact.meta.id, path: rulePath(entry) });
  }

  const skillEntries: { id: string; path: string }[] = [];
  for (const entry of selection.skills) {
    const dir = skillDir(entry);
    files.push({ path: posix.join(dir, 'SKILL.md'), copyFrom: entry.artifact.path });
    skillEntries.push({ id: entry.artifact.meta.id, path: dir });
    for (const extra of entry.artifact.files) {
      files.push({
        path: posix.join(dir, extra.split(sep).join('/')),
        copyFrom: join(entry.artifact.dir, extra),
      });
    }
  }

  const commandEntries: { id: string; path: string }[] = [];
  for (const entry of selection.commands) {
    files.push({ path: commandPath(entry), copyFrom: entry.artifact.path });
    commandEntries.push({ id: entry.artifact.meta.id, path: commandPath(entry) });
  }

  const usedSources = new Set(
    [
      ...selection.rules,
      ...selection.skills,
      ...selection.commands,
      ...selection.agentMd,
    ]
      .map((entry) => entry.artifact.provenance?.source)
      .filter((source): source is string => source !== undefined),
  );
  const used = imported.filter((source) => usedSources.has(source.name));

  const manifest: Manifest = {
    generator: `agent-stack@${generatorVersion}`,
    generatedAt: new Date().toISOString(),
    stack: stack.technologies.map((tech) => ({ id: tech.id, origin: tech.origin })),
    rules: ruleEntries.map(({ id, path }) => ({ id, path })),
    skills: skillEntries,
    commands: commandEntries,
    extras: [],
    imported: used.map(({ name, repo, ref, license, licenseUrl, copyright }) => ({
      source: name,
      repo,
      ref,
      license,
      licenseUrl,
      copyright,
    })),
  };

  // The validator stops a run that selects two; this only ever sees one.
  const template = selection.agentMd[0];
  const agentsMd = template
    ? { path: AGENTS_MD_PATH, copyFrom: template.artifact.path }
    : undefined;

  return { files, manifest, ...(agentsMd ? { agentsMd } : {}) };
}

/**
 * Where each selected artifact would land, worked out before anything is
 * written.
 *
 * The picker and the collision check both need to talk about an artifact by the
 * path it occupies, and this module already owns that mapping — deriving it a
 * second time elsewhere is how the two would drift apart. The AGENTS.md
 * template has no path: an AGENTS.md already in the project is the expected
 * case, not a collision, and is simply left alone.
 */
export interface ArtifactTarget {
  id: string;
  type: ArtifactType;
  path?: string;
}

export function artifactTargets(selection: Selection): ArtifactTarget[] {
  return [
    ...selection.rules.map((entry) => ({
      id: entry.artifact.meta.id,
      type: 'rule' as const,
      path: rulePath(entry),
    })),
    ...selection.skills.map((entry) => ({
      id: entry.artifact.meta.id,
      type: 'skill' as const,
      path: skillDir(entry),
    })),
    ...selection.commands.map((entry) => ({
      id: entry.artifact.meta.id,
      type: 'command' as const,
      path: commandPath(entry),
    })),
    ...selection.agentMd.map((entry) => ({
      id: entry.artifact.meta.id,
      type: 'agent-md' as const,
    })),
  ];
}
