import { join, posix } from 'node:path';
import { stringify as stringifyYaml } from 'yaml';
import type { ResolvedStack } from './resolver.js';
import type { Selection, SelectedArtifact } from './selector.js';

export const MANIFEST_PATH = posix.join('.claude', 'aidd-manifest.json');
export const BEGIN_MARKER = '<!-- aidd:begin - generated by open-aidd, do not edit by hand -->';
export const END_MARKER = '<!-- aidd:end -->';

export interface PlannedFile {
  path: string;
  /** Inline contents, or a source path to copy verbatim (skill attachments). */
  contents?: string;
  copyFrom?: string;
}

export interface Manifest {
  generator: string;
  generatedAt: string;
  stack: { id: string; version?: string; origin: string }[];
  rules: { id: string; path: string }[];
  skills: { id: string; path: string }[];
}

export interface ComposedOutput {
  files: PlannedFile[];
  /** Paths owned by the previous run that this run no longer emits. */
  manifest: Manifest;
  claudeMdBlock: string;
}

function rulePath(entry: SelectedArtifact): string {
  const prefix = String(entry.artifact.meta.priority).padStart(2, '0');
  return posix.join('.claude', 'rules', `${prefix}-${entry.artifact.meta.id}.md`);
}

function skillDir(entry: SelectedArtifact): string {
  return posix.join('.claude', 'skills', entry.artifact.meta.id);
}

function ruleFile(entry: SelectedArtifact): string {
  const { meta, body, source } = entry.artifact;
  const origin =
    entry.matchedBy.length > 0 ? `applies to: ${entry.matchedBy.join(', ')}` : 'applies to: all projects';
  return [
    `<!-- generated by open-aidd from knowledge/${source} - edit the knowledge base, not this file -->`,
    `<!-- ${origin} -->`,
    '',
    `# ${meta.name}`,
    '',
    body,
    '',
  ].join('\n');
}

/**
 * A knowledge-base SKILL.md carries both Claude's fields and open-aidd's
 * selection metadata; only Claude's fields belong in the emitted skill.
 */
function skillFile(entry: SelectedArtifact): string {
  const { meta, body, source } = entry.artifact;
  const frontMatter = stringifyYaml({ name: meta.name, description: meta.description }).trim();
  return [
    '---',
    frontMatter,
    '---',
    '',
    `<!-- generated by open-aidd from knowledge/${source} - edit the knowledge base, not this file -->`,
    '',
    body,
    '',
  ].join('\n');
}

function claudeMdBlock(rules: { path: string; name: string }[]): string {
  const lines = [
    BEGIN_MARKER,
    '',
    '## Project rules',
    '',
    ...rules.map((rule) => `@${rule.path}`),
    '',
    END_MARKER,
  ];
  return lines.join('\n');
}

/** Merge the managed block into an existing CLAUDE.md without touching the rest. */
export function mergeClaudeMd(existing: string | undefined, block: string): string {
  if (!existing || existing.trim() === '') {
    return `${block}\n`;
  }
  const begin = existing.indexOf(BEGIN_MARKER);
  const end = existing.indexOf(END_MARKER);
  if (begin >= 0 && end > begin) {
    const before = existing.slice(0, begin);
    const after = existing.slice(end + END_MARKER.length);
    return `${before}${block}${after}`;
  }
  const separator = existing.endsWith('\n') ? '\n' : '\n\n';
  return `${existing}${separator}${block}\n`;
}

export function compose(stack: ResolvedStack, selection: Selection, generatorVersion: string): ComposedOutput {
  const files: PlannedFile[] = [];
  const ruleEntries = selection.rules.map((entry) => ({
    id: entry.artifact.meta.id,
    name: entry.artifact.meta.name,
    path: rulePath(entry),
  }));

  for (const entry of selection.rules) {
    files.push({ path: rulePath(entry), contents: ruleFile(entry) });
  }

  const skillEntries: { id: string; path: string }[] = [];
  for (const entry of selection.skills) {
    const dir = skillDir(entry);
    files.push({ path: posix.join(dir, 'SKILL.md'), contents: skillFile(entry) });
    skillEntries.push({ id: entry.artifact.meta.id, path: dir });
    for (const extra of entry.artifact.meta.files) {
      files.push({
        path: posix.join(dir, extra),
        copyFrom: join(entry.artifact.dir, extra),
      });
    }
  }

  const manifest: Manifest = {
    generator: `open-aidd@${generatorVersion}`,
    generatedAt: new Date().toISOString(),
    stack: stack.technologies.map((tech) => ({
      id: tech.id,
      version: tech.version,
      origin: tech.origin,
    })),
    rules: ruleEntries.map(({ id, path }) => ({ id, path })),
    skills: skillEntries,
  };

  files.push({ path: MANIFEST_PATH, contents: `${JSON.stringify(manifest, null, 2)}\n` });

  return { files, manifest, claudeMdBlock: claudeMdBlock(ruleEntries) };
}
