import { join, posix, sep } from 'node:path';
import type { ArtifactType } from './schema.js';
import type { ImportedSource } from './upstream.js';
import type { ResolvedStack } from './resolver.js';
import type { Selection, SelectedArtifact } from './selector.js';

export const MANIFEST_PATH = posix.join('.claude', 'agent-stack-manifest.json');
export const BEGIN_MARKER = '<!-- agent-stack:begin - generated by agent-stack, do not edit by hand -->';
export const END_MARKER = '<!-- agent-stack:end -->';

export interface PlannedFile {
  path: string;
  /** Inline contents — only the manifest, which agent-stack does author. */
  contents?: string;
  /** A knowledge file, copied byte for byte. Every artifact takes this path. */
  copyFrom?: string;
}

export interface Manifest {
  generator: string;
  generatedAt: string;
  stack: { id: string; origin: string }[];
  rules: { id: string; path: string }[];
  skills: { id: string; path: string }[];
  commands: { id: string; path: string }[];
  /** Other generated paths this run owns, e.g. third-party licence notices. */
  extras: string[];
  /**
   * Content this project carries from other repositories, with the copyright and
   * licence it is redistributed under. This is where the upstream notices live.
   */
  imported: {
    source: string;
    repo: string;
    ref: string;
    license: string;
    licenseUrl: string;
    copyright: string;
  }[];
}

export interface ComposedOutput {
  files: PlannedFile[];
  /** Paths owned by the previous run that this run no longer emits. */
  manifest: Manifest;
  claudeMdBlock: string;
}

/** The file's own name under `knowledge/` is the name emitted under `.claude/`. */
/**
 * Where an artifact lands. The path under `knowledge/` decided the id, and the
 * id is the filename here — nothing about the file itself is inspected.
 */
function rulePath(entry: SelectedArtifact): string {
  return posix.join('.claude', 'rules', `${entry.artifact.meta.id}.md`);
}

function skillDir(entry: SelectedArtifact): string {
  return posix.join('.claude', 'skills', entry.artifact.meta.id);
}

function commandPath(entry: SelectedArtifact): string {
  return posix.join('.claude', 'commands', `${entry.artifact.meta.id}.md`);
}

/**
 * Prepare a fragment for splicing into someone else's document.
 *
 * Two removals, and only because the text is being inlined rather than copied:
 * a YAML block would be nonsense partway down a Markdown file, and the
 * fragment's own `# Title` would give the project a second `h1` — the imported
 * one is literally titled "CLAUDE.md".
 */
function inlineFragment(contents: string): string {
  const withoutFrontMatter = contents.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/, '');
  const body = withoutFrontMatter.trim();
  return body.startsWith('# ') ? body.slice(body.indexOf('\n') + 1).trimStart() : body;
}

/**
 * The managed block: guidance every project needs is inlined so it is in
 * context without a hop, and the selected rules follow as `@`-imports, in the
 * order their filenames sort.
 */
function claudeMdBlock(fragments: SelectedArtifact[], rules: { path: string }[]): string {
  const lines: string[] = [BEGIN_MARKER, ''];

  for (const fragment of fragments) {
    lines.push(inlineFragment(fragment.artifact.contents ?? ''), '');
  }

  if (rules.length > 0) {
    lines.push('## Project rules', '', ...rules.map((rule) => `@${rule.path}`), '');
  }
  lines.push(END_MARKER);
  return lines.join('\n');
}

/** Merge the managed block into an existing CLAUDE.md without touching the rest. */
export function mergeClaudeMd(existing: string | undefined, block: string): string {
  if (!existing || existing.trim() === '') {
    return `${block}\n`;
  }
  const begin = existing.indexOf(BEGIN_MARKER);
  const end = existing.indexOf(END_MARKER);
  if (begin >= 0 && end > begin) {
    const before = existing.slice(0, begin);
    const after = existing.slice(end + END_MARKER.length);
    return `${before}${block}${after}`;
  }
  const separator = existing.endsWith('\n') ? '\n' : '\n\n';
  return `${existing}${separator}${block}\n`;
}

export function compose(
  stack: ResolvedStack,
  selection: Selection,
  generatorVersion: string,
  imported: ImportedSource[] = [],
): ComposedOutput {
  const files: PlannedFile[] = [];

  const ruleEntries = selection.rules.map((entry) => ({
    id: entry.artifact.meta.id,
    path: rulePath(entry),
  }));
  for (const entry of selection.rules) {
    files.push({ path: rulePath(entry), copyFrom: entry.artifact.path });
  }

  const skillEntries: { id: string; path: string }[] = [];
  for (const entry of selection.skills) {
    const dir = skillDir(entry);
    files.push({ path: posix.join(dir, 'SKILL.md'), copyFrom: entry.artifact.path });
    skillEntries.push({ id: entry.artifact.meta.id, path: dir });
    for (const extra of entry.artifact.files) {
      files.push({
        path: posix.join(dir, extra.split(sep).join('/')),
        copyFrom: join(entry.artifact.dir, extra),
      });
    }
  }

  const commandEntries: { id: string; path: string }[] = [];
  for (const entry of selection.commands) {
    files.push({ path: commandPath(entry), copyFrom: entry.artifact.path });
    commandEntries.push({ id: entry.artifact.meta.id, path: commandPath(entry) });
  }

  const usedSources = new Set(
    [...selection.rules, ...selection.skills, ...selection.commands, ...selection.claudeMd]
      .map((entry) => entry.artifact.provenance?.source)
      .filter((source): source is string => source !== undefined),
  );
  const used = imported.filter((source) => usedSources.has(source.name));

  const manifest: Manifest = {
    generator: `agent-stack@${generatorVersion}`,
    generatedAt: new Date().toISOString(),
    stack: stack.technologies.map((tech) => ({ id: tech.id, origin: tech.origin })),
    rules: ruleEntries.map(({ id, path }) => ({ id, path })),
    skills: skillEntries,
    commands: commandEntries,
    extras: [],
    imported: used.map(({ name, repo, ref, license, licenseUrl, copyright }) => ({
      source: name,
      repo,
      ref,
      license,
      licenseUrl,
      copyright,
    })),
  };

  files.push({ path: MANIFEST_PATH, contents: `${JSON.stringify(manifest, null, 2)}\n` });

  return { files, manifest, claudeMdBlock: claudeMdBlock(selection.claudeMd, ruleEntries) };
}

/**
 * Where each selected artifact would land, worked out before anything is
 * written.
 *
 * The picker and the collision check both need to talk about an artifact by the
 * path it occupies, and this module already owns that mapping — deriving it a
 * second time elsewhere is how the two would drift apart. A `claude-md`
 * fragment has no path because it is spliced into a document rather than
 * copied.
 */
export interface ArtifactTarget {
  id: string;
  type: ArtifactType;
  path?: string;
}

export function artifactTargets(selection: Selection): ArtifactTarget[] {
  return [
    ...selection.rules.map((entry) => ({
      id: entry.artifact.meta.id,
      type: 'rule' as const,
      path: rulePath(entry),
    })),
    ...selection.skills.map((entry) => ({
      id: entry.artifact.meta.id,
      type: 'skill' as const,
      path: skillDir(entry),
    })),
    ...selection.commands.map((entry) => ({
      id: entry.artifact.meta.id,
      type: 'command' as const,
      path: commandPath(entry),
    })),
    ...selection.claudeMd.map((entry) => ({
      id: entry.artifact.meta.id,
      type: 'claude-md' as const,
    })),
  ];
}
